name: 'Fetch and process data to build OTP graph'

runs:
  using: 'composite'
  steps:
    - name: Fetch GTFS zip files
      working-directory: deployment/dataproc/gtfs-feed-fetcher
      run: docker compose run --rm gtfs-feed-fetcher ./fetch_feeds.py
      shell: bash

      # TODO 1397: Edit SEPTA bus routes.txt files to bring back to OTPv1 support,
      # Confirm no errors in .html files, run feedvalidator script
    
    - name: Extend date range
      working-directory: deployment/dataproc/gtfs-feed-fetcher
      run: docker compose run --rm gtfs-feed-fetcher ./extend_effective_dates.py --feeds=patco.zip,septa_bus.zip,septa_rail.zip,dart.zip
      shell: bash
    
    - name: Copy GTFS file to otp_data
      run: cp deployment/dataproc/gtfs-feed-fetcher/gtfs/{patco_extended.zip,septa_bus_extended.zip,septa_rail_extended.zip,dart_extended.zip,nj_bus.zip,nj_rail.zip} ./otp_data/
      shell: bash

    - name: Fetch OSM files
      working-directory: deployment/dataproc/osm
      run: docker compose run --rm osm ./download-osm-data.sh
      shell: bash
    
    - name: Process OSM files
      working-directory: deployment/dataproc/osm
      run: docker compose run --rm osm ./combine-and-clip.sh
      shell: bash
    
    - name: Copy OSM .pbf file to otp_data
      run: cp deployment/dataproc/osm/cac.pbf ./otp_data/
      shell: bash
    
    - name: Fetch elevation file from S3
      run: aws s3 cp "s3://$CAC_OTP_DATA_BUCKET/cac.tif" "otp_data/cac.tif"
      shell: bash
