---
- name: Install Sass
  gem: name=sass
       version={{ app_sass_version }}
       user_install=no
       state=present

- name: Install Compass
  gem: name=compass
       user_install=no
       state=present

- name: Install bower and gulp
  npm: name={{ item }} state=present global=yes
  with_items:
    - bower
    - gulp

- name: Install npm prereqs
  npm: path="{{ gulp_dir }}" state=present
  sudo: no

- name: Install application javascript dependencies (bower)
  command: bower install
  sudo: no
  args:
    chdir: "{{ gulp_dir }}"

- name: Create Static Directories
  file: path="{{ gulp_dir }}/{{ item }}" state=directory mode=0666
  sudo: no
  with_items:
    - "dist/scripts"

- name: Create static files (staging/production)
  command: gulp build
  sudo: no
  args:
    chdir: "{{ gulp_dir }}"
