---
- name: Install Sass
  gem: name=sass
       version={{ app_sass_version }}
       user_install=no
       state=present

- name: Install Compass
  gem: name=compass
       user_install=no
       state=present

- name: Install bower and gulp
  command: npm install -g bower gulp

- name: Install npm prereqs
  command: npm install
  sudo: no
  args:
    chdir: "{{ gulp_dir }}"

- name: Install application javascript dependencies (bower)
  command: bower install
  sudo: no
  args:
    chdir: "{{ gulp_dir }}"

- name: Create static files (staging/production)
  command: gulp build
  sudo: no
  args:
    chdir: "{{ gulp_dir }}"

