---
- name: Clear out the NPM artifacts when in production (want a fresh set)
  file: path="{{ root_src_dir }}/node_modules" state=absent
  become: yes
  when: production

- name: Install NPM dependencies
  command: npm install chdir="{{ root_src_dir }}"
  become: no

- name: Create Static Directory
  file: path="{{ root_static_dir }}" state=directory mode=0755 owner="{{ app_username }}"
  become: yes

- name: Install application javascript dependencies with bower
  command: npm run bower-install
  become: no
  args:
    chdir: "{{ root_src_dir }}"

- name: Build javascript assets -- development
  command: npm run gulp-development
  become: no
  args:
    chdir: "{{ root_src_dir }}"
  when: not production and not test

- name: Build javascript assets -- production
  command: npm run gulp-production
  become: no
  args:
    chdir: "{{ root_src_dir }}"
  when: production or test
