---
- name: Install Sass
  gem: name=sass
       version={{ app_sass_version }}
       user_install=no
       state=present

- name: Install Compass
  gem: name=compass
       user_install=no
       state=present

- name: Install NPM dependencies
  npm: path="{{ gulp_dir }}" state=present
  sudo: no

- name: Create Static Directories
  file: path="{{ gulp_dir }}/{{ item }}" state=directory mode=0755
  sudo: no
  with_items:
    - "dist/scripts"
    - ".tmp/styles"

- name: Install application javascript dependencies with bower
  command: npm run bower-install
  sudo: no
  args:
    chdir: "{{ gulp_dir }}"

- name: Create static files (staging/production)
  command: npm run gulp-build
  sudo: no
  args:
    chdir: "{{ gulp_dir }}"
