---
# # Note bzip2 only installed here as workaround for unresolved but closed phantomjs
# install issue: https://github.com/Medium/phantomjs/issues/659
- name: Install packages
  apt: name={{ item }} state=present
  with_items:
    - binutils
    - bzip2
    - gdal-bin
    - libpq-dev
    - libproj-dev
    - python-dev
    - libjpeg-dev

- name: Install pip packages
  pip: name={{ item.name }} version={{ item.version }}
  with_items: "{{ cac_python_dependencies }}"

  # Putting 'editable: false' in the entry in cac_python_dependencies should make it install
  # non-editable, but it's getting ignored
- name: Install django-wpadmin manually to work around ansible bug
  command: pip install --upgrade 'git+https://github.com/azavea/django-wpadmin@v1.11#egg=django-wpadmin'

- name: Touch log file and set permissions
  file: path={{ app_log }} state=touch owner={{ app_username }} group={{ app_username }} mode=0664

- name: Create configuration file directory
  file: path={{ root_conf_dir }}
        owner={{ app_username }}
        group={{ app_username }}
        mode=0750
        state=directory

- name: Create app media directory
  file: path={{ root_media_dir }}
        owner={{ app_username }}
        group={{ app_username }}
        mode=0775
        state=directory

- name: Write secrets file
  template: src=cac_secrets.j2 dest=/etc/cac_secrets
  when: develop or production
  notify: Restart cac-tripplanner-app

- name: Configure Gunicorn settings
  template: src=gunicorn-cac-tripplanner.py.j2 dest={{ root_conf_dir }}/gunicorn.py
  notify: Restart cac-tripplanner-app

- name: Configure service definition
  template: src=upstart-cac-tripplanner-app.conf.j2 dest=/etc/init/cac-tripplanner-app.conf
  notify: Restart cac-tripplanner-app

- name: Run migrations
  django_manage: command=migrate
                 app_path=/opt/app/python/cac_tripplanner
  notify: Restart cac-tripplanner-app
  when: develop or test

- name: Run collectstatic
  django_manage: command=collectstatic
                 app_path=/opt/app/python/cac_tripplanner

- name: Copy media assets
  copy: src=../../python/cac_tripplanner/default_media
        dest=/media/cac
        owner={{ app_username }}
        group={{ app_username }}
  when: develop or test

- name: Copy nginx config
  template: src=nginx-default.j2 dest=/etc/nginx/sites-available/default
  notify: Restart nginx

- { import_tasks: jslibs.yml }

- { import_tasks: dev-test-dependencies.yml, when: develop or test }
