---
- name: Install packages
  apt: name={{ item }} state=present
  with_items:
    - libpq-dev
    - python-dev
    - libproj-dev
    - binutils
    - gdal-bin
    - gunicorn

- name: Install pip packages
  pip: name={{ item.name }} version={{ item.version }}
  with_items: cac_python_dependencies


- name: Delete example gunicorn config
  file: name={{ item }} state=absent
  with_items:
    - /etc/gunicorn.d/django.example
    - /etc/gunicorn.d/wsgi.example
  notify: Restart gunicorn

- name: Install gunicorn config
  template: src=app.j2 dest=/etc/gunicorn.d/app
  notify: Restart gunicorn

- name: Run migrations
  django_manage: command=migrate
                 app_path=/opt/app/python/cac_tripplanner
  notify: Restart gunicorn

- name: Copy nginx config
  template: src=nginx-default.j2 dest=/etc/nginx/sites-available/default
  notify: Restart nginx

- { include: jslibs.yml }

- { include: dev-test-dependencies.yml, when: develop or test }
