---
- name: Install packages
  apt: name={{ item }} state=present
  with_items:
    - libpq-dev
    - python-dev
    - libproj-dev
    - binutils
    - gdal-bin
    - gunicorn

- name: Install pip packages
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    - { name: 'pyyaml', version: '3.11' }
    - { name: 'django', version: '1.7.3' }
    - { name: 'psycopg2', version: '2.5.4' }
    - { name: 'pytz', version: '2014.10' }
    - { name: 'django-ckeditor', version: '4.4.7' }

- name: Delete example gunicorn config
  file: name={{ item }} state=absent
  with_items:
    - /etc/gunicorn.d/django.example
    - /etc/gunicorn.d/wsgi.example
  notify: Restart gunicorn

- name: Install gunicorn config
  template: src=app.j2 dest=/etc/gunicorn.d/app
  notify: Restart gunicorn

- name: Run migrations
  django_manage: command=migrate
                 app_path=/opt/app/python/cac_tripplanner
  notify: Restart gunicorn

- name: Copy nginx config
  copy: src=default dest=/etc/nginx/sites-available/default
  notify: Restart nginx

- { include: jslibs.yml }

