---
  dependencies:
    - { role: "azavea.git" }
    - { role: "azavea.nginx" }
    - { role: "azavea.nodejs" }
    - { role: "azavea.ruby", ruby_development: True }
    - { role: "azavea.virtualenv" }
