---
- name: Install maven
  apt: pkg=maven state=present

- name: Download OpenTripPlanner
  git: repo=git://github.com/opentripplanner/OpenTripPlanner.git
       dest=/opt/otp
       version=0.11.x

- name: Compile OpenTripPlanner
  shell: cd /opt/otp/ && mvn clean package
  args:
    creates: /opt/otp/otp-core/target/otp.jar

- name: Create OTP User
  user: name={{ otp_user }}

- name: Install upstart service
  template: src=otp.conf dest=/etc/init/otp.conf
  notify: Restart OpenTripPlanner

- name: Create Directory for OSM and GTFS
  file: path=/usr/local/share/osm_gtfs/ state=directory

- name: Download Philadelphia OSM Data
  get_url: url=https://s3.amazonaws.com/metro-extracts.mapzen.com/philadelphia_pennsylvania.osm.pbf dest=/usr/local/share/osm_gtfs/phila.osm.pdf

#- name: Build OTP Graph
#  shell: cd /opt/otp/ && ./otp --build /usr/local/share/osm_gtfs/
