# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0021_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedEvent',
        ),
    ]
