# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 17:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0024_default_destination_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='accessible',
            field=models.BooleanField(default=False, help_text=b'Is it ADA accessible?'),
        ),
        migrations.AddField(
            model_name='event',
            name='accessible',
            field=models.BooleanField(default=False, help_text=b'Is it ADA accessible?'),
        ),
    ]
