# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 19:27


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0025_auto_20171201_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
