# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0028_default_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='watershed_alliance',
            field=models.BooleanField(default=False, help_text=(b'Does this location belong ', b'to the Alliance for Watershed Education?')),
        ),
    ]
