# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 19:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0031_remove_relax_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='watershed_alliance',
            field=models.BooleanField(default=False, help_text=b'\n        Does this location belong to the <a target="_blank"\n        href="https://www.watershedalliance.org/centers/">\n        Alliance for Watershed Education</a>?'),
        ),
    ]
