# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0032_auto_20171220_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='activities',
            field=models.ManyToManyField(blank=True, to='destinations.Activity'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='categories',
            field=models.ManyToManyField(blank=True, to='destinations.DestinationCategory'),
        ),
        migrations.AlterField(
            model_name='event',
            name='activities',
            field=models.ManyToManyField(blank=True, to='destinations.Activity'),
        ),
    ]
