# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 18:25


import destinations.models
from django.db import migrations
import image_cropping.fields

def set_new_images(apps, schema_editor):
    Destination = apps.get_model('destinations', 'Destination')
    Event = apps.get_model('destinations', 'Event')
    for place in Destination.objects.all():
        place.image_raw = place.image
        place.wide_image_raw = place.wide_image
        place.save()
    for event in Event.objects.all():
        event.image_raw = event.image
        event.wide_image_raw = event.wide_image
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0034_rename_canoeing'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image_raw',
            field=image_cropping.fields.ImageCropField(null=True, upload_to=destinations.models.generate_filename, verbose_name='image file'),
        ),
        migrations.AddField(
            model_name='destination',
            name='wide_image_raw',
            field=image_cropping.fields.ImageCropField(null=True, upload_to=destinations.models.generate_filename, verbose_name='wide image file'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_raw',
            field=image_cropping.fields.ImageCropField(null=True, upload_to=destinations.models.generate_filename, verbose_name='image file'),
        ),
        migrations.AddField(
            model_name='event',
            name='wide_image_raw',
            field=image_cropping.fields.ImageCropField(null=True, upload_to=destinations.models.generate_filename, verbose_name='wide image file'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=image_cropping.fields.ImageRatioField('image_raw', '310x155', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='The small image. Will be displayed at 310x155.', hide_image_field=False, size_warning=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='wide_image',
            field=image_cropping.fields.ImageRatioField('wide_image_raw', '680x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='The large image. Will be displayed at 680x400.', hide_image_field=False, size_warning=True, verbose_name='wide image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=image_cropping.fields.ImageRatioField('image_raw', '310x155', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='The small image. Will be displayed at 310x155.', hide_image_field=False, size_warning=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='wide_image',
            field=image_cropping.fields.ImageRatioField('wide_image_raw', '680x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='The large image. Will be displayed at 680x400.', hide_image_field=False, size_warning=True, verbose_name='wide image'),
        ),

        migrations.RunPython(set_new_images, migrations.RunPython.noop),
    ]
