# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 16:56


from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0036_extradestinationpicture_extraeventpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=image_cropping.fields.ImageRatioField('image_raw', '310x155', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='The small image. Will be displayed at 310x155', hide_image_field=False, size_warning=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='wide_image',
            field=image_cropping.fields.ImageRatioField('wide_image_raw', '680x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='The large image. Will be displayed at 680x400', hide_image_field=False, size_warning=True, verbose_name='wide image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=image_cropping.fields.ImageRatioField('image_raw', '310x155', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='The small image. Will be displayed at 310x155', hide_image_field=False, size_warning=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='wide_image',
            field=image_cropping.fields.ImageRatioField('wide_image_raw', '680x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='The large image. Will be displayed at 680x400', hide_image_field=False, size_warning=True, verbose_name='wide image'),
        ),
    ]
