# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 20:39
from __future__ import unicode_literals

import destinations.models
from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0037_auto_20180412_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extradestinationpicture',
            name='image_raw',
            field=image_cropping.fields.ImageCropField(upload_to=destinations.models.generate_filename, verbose_name=b'image file'),
        ),
        migrations.AlterField(
            model_name='extraeventpicture',
            name='image_raw',
            field=image_cropping.fields.ImageCropField(upload_to=destinations.models.generate_filename, verbose_name=b'image file'),
        ),
    ]
