# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 18:52


from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('destinations', '0041_auto_20180418_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('is_event', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_uuid', models.UUIDField(editable=False)),
                ('flag', models.CharField(choices=[(b'been', b'Been'), (b'want_to_go', b'Want to go'), (b'not_interested', b'Not interested'), (b'liked', b'Liked'), (b'', b'')], max_length=32)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
