# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 17:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0043_auto_20180530_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userflag',
            name='flag',
            field=models.CharField(blank=True, choices=[(b'been', b'Been'), (b'want_to_go', b'Want to go'), (b'not_interested', b'Not interested'), (b'liked', b'Liked'), (b'', b'')], db_index=True, max_length=32),
        ),
    ]
