# Generated by Django 2.2.4 on 2019-08-29 19:29

import destinations.models
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0046_prepopulate_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='accessible',
            field=models.BooleanField(default=False, help_text='Is it ADA accessible?'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='address',
            field=models.CharField(help_text='The map automatically updates as the address is typed, but may be overridden manually if incorrect.', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(default='Philadelphia', max_length=40),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image_raw',
            field=image_cropping.fields.ImageCropField(help_text='Save and return to editing this record to see an uploaded image and\nto change how the image is cropped.', upload_to=destinations.models.generate_filename, verbose_name='image file'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='state',
            field=models.CharField(default='PA', max_length=20),
        ),
        migrations.AlterField(
            model_name='destination',
            name='watershed_alliance',
            field=models.BooleanField(default=False, help_text='\n        Does this location belong to the <a target="_blank"\n        href="https://www.watershedalliance.org/centers/">\n        Alliance for Watershed Education</a>?'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='wide_image_raw',
            field=image_cropping.fields.ImageCropField(help_text='Save and return to editing this record to see an uploaded image and\nto change how the image is cropped.', upload_to=destinations.models.generate_filename, verbose_name='wide image file'),
        ),
        migrations.AlterField(
            model_name='event',
            name='accessible',
            field=models.BooleanField(default=False, help_text='Is it ADA accessible?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_raw',
            field=image_cropping.fields.ImageCropField(help_text='Save and return to editing this record to see an uploaded image and\nto change how the image is cropped.', upload_to=destinations.models.generate_filename, verbose_name='image file'),
        ),
        migrations.AlterField(
            model_name='event',
            name='wide_image_raw',
            field=image_cropping.fields.ImageCropField(help_text='Save and return to editing this record to see an uploaded image and\nto change how the image is cropped.', upload_to=destinations.models.generate_filename, verbose_name='wide image file'),
        ),
        migrations.AlterField(
            model_name='extradestinationpicture',
            name='image_raw',
            field=image_cropping.fields.ImageCropField(help_text='Save and return to editing this record to see an uploaded image and\nto change how the image is cropped.', upload_to=destinations.models.generate_filename, verbose_name='image file'),
        ),
        migrations.AlterField(
            model_name='extraeventpicture',
            name='image_raw',
            field=image_cropping.fields.ImageCropField(help_text='Save and return to editing this record to see an uploaded image and\nto change how the image is cropped.', upload_to=destinations.models.generate_filename, verbose_name='image file'),
        ),
        migrations.AlterField(
            model_name='userflag',
            name='flag',
            field=models.CharField(blank=True, choices=[('been', 'Been'), ('want_to_go', 'Want to go'), ('not_interested', 'Not interested'), ('liked', 'Liked'), ('', '')], db_index=True, max_length=32),
        ),
    ]
