# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-29 18:05
from __future__ import unicode_literals

from django.db import migrations, models


def move_event_destinations_to_multiple(apps, schema_editor):
    """Move event destination to new set of multiple destinations."""
    Event = apps.get_model('destinations', 'Event')
    events = Event.objects.all()
    for event in events:
        if event.destination:
            event.destinations.add(event.destination)
            event.save()


def move_event_destinations_to_single(apps, schema_editor):
    """Move event destination from new set of multiple destinations.

    Use the first destination for the event.
    """
    Event = apps.get_model('destinations', 'Event')
    events = Event.objects.all()
    for event in events:
        if event.destinations.count() > 0:
            event.destination = event.destinations.first()
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0046_prepopulate_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='event_only',
            field=models.BooleanField(default=False, help_text=b'\n        Should this location only appear with its associated event(s)?'),
        ),
        migrations.AddField(
            model_name='event',
            name='destinations',
            field=models.ManyToManyField(blank=True, to='destinations.Destination'),
        ),
        migrations.RunPython(move_event_destinations_to_multiple, move_event_destinations_to_single),
        migrations.RemoveField(
            model_name='event',
            name='destination',
        ),
    ]
