# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-30 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0049_auto_20190827_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdestination',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='destinations.Destination'),
        ),
        migrations.AlterField(
            model_name='tourdestination',
            name='related_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_destinations', to='destinations.Tour'),
        ),
    ]
