# Generated by Django 2.2.4 on 2019-09-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0047_auto_20190829_1529'),
        ('destinations', '0049_auto_20190827_1709'),
    ]

    operations = [
    ]
