# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-05 15:47
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0051_auto_20190830_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
