# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-05 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0052_tour_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
