# Generated by Django 2.2.4 on 2019-09-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0053_auto_20190905_1523'),
        ('destinations', '0047_auto_20190829_1529'),
    ]

    operations = [
    ]
