# Generated by Django 2.2.4 on 2019-09-06 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0054_merge_20190905_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=1)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='destinations.Destination')),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='tourdestination',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='tour',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='tourdestination',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tourdestination',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='destinations',
            field=models.ManyToManyField(blank=True, to='destinations.EventDestination'),
        ),
        migrations.AddField(
            model_name='eventdestination',
            name='related_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_destinations', to='destinations.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='eventdestination',
            unique_together={('destination', 'related_event')},
        ),
    ]
