# Generated by Django 2.2.4 on 2019-09-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0055_auto_20190906_1705'),
        ('destinations', '0050_merge_20190909_0932'),
    ]

    operations = [
    ]
