# Generated by Django 2.2.4 on 2019-09-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0058_add_event_destinations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='destinations',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='destinations',
        ),
    ]
