---
- name: Install GCC for PostgreSQL support role
  apt:
    state: present
    pkg: gcc

- name: Dynamically include PostgreSQL support role
  include_role:
    name: azavea.postgresql-support

- name: Install PostGIS extension from source
  import_tasks: install-postgis-from-source.yml

- name: Create postgres database
  postgresql_db: name={{ postgres_db }}
  become_user: postgres

- name: Create postgres user
  postgresql_user: db={{ postgres_db }}
                   name={{ postgres_user }}
                   password={{ postgres_password }}
                   role_attr_flags=SUPERUSER
  become_user: postgres

- name: Add PostGIS extension
  become_user: postgres
  command: psql {{ postgres_db }} -c "CREATE EXTENSION postgis"
  register: psql_result
  failed_when: >
    psql_result.rc != 0 and ("already exists" not in psql_result.stderr)
  changed_when: "psql_result.rc == 0"
