# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 18:29
from __future__ import unicode_literals

import cms.models
from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0010_auto_20170201_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='narrow_image_raw',
            field=image_cropping.fields.ImageCropField(null=True, upload_to=cms.models.generate_filename, verbose_name=b'narrow image file'),
        ),
        migrations.AddField(
            model_name='article',
            name='wide_image_raw',
            field=image_cropping.fields.ImageCropField(null=True, upload_to=cms.models.generate_filename, verbose_name=b'wide image file'),
        ),
        migrations.AlterField(
            model_name='article',
            name='narrow_image',
            field=image_cropping.fields.ImageRatioField(b'narrow_image', '310x218', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=b'The small image. Will be displayed at 310x218.', hide_image_field=False, size_warning=True, verbose_name='narrow image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='wide_image',
            field=image_cropping.fields.ImageRatioField(b'wide_image_raw', '680x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=b'The large image. Will be displayed at 680x200.', hide_image_field=False, size_warning=True, verbose_name='wide image'),
        ),
    ]
