# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 20:17
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0011_auto_20180410_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='narrow_image',
            field=image_cropping.fields.ImageRatioField(b'narrow_image', '310x218', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=b'The small image. Will be displayed at 310x218', hide_image_field=False, size_warning=True, verbose_name='narrow image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='wide_image',
            field=image_cropping.fields.ImageRatioField(b'wide_image_raw', '680x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=b'The large image. Will be displayed at 680x200', hide_image_field=False, size_warning=True, verbose_name='wide image'),
        ),
    ]
