# Generated by Django 2.2.4 on 2019-08-29 19:29

import cms.models
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0015_prepopulate_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('prof', 'Community Profile'), ('tips', 'Tips and Tricks')], max_length=4),
        ),
        migrations.AlterField(
            model_name='article',
            name='narrow_image_raw',
            field=image_cropping.fields.ImageCropField(help_text='Save and return to editing this record to see an uploaded image and\nto change how the image is cropped.', null=True, upload_to=cms.models.generate_filename, verbose_name='narrow image file'),
        ),
        migrations.AlterField(
            model_name='article',
            name='wide_image_raw',
            field=image_cropping.fields.ImageCropField(help_text='Save and return to editing this record to see an uploaded image and\nto change how the image is cropped.', null=True, upload_to=cms.models.generate_filename, verbose_name='wide image file'),
        ),
    ]
