---
- name: Create Directory for OSM and GTFS
  file: path={{ otp_data_dir }} state=directory

- name: Copy Feed Validator
  copy: src=validate_feed.py dest="{{ otp_data_dir }}"

- name: Install AuthBind (for serving OTP on port 80)
  apt: pkg=authbind state=present

- name: Touch AuthBind file if it does not exist
  command: touch /etc/authbind/byport/80
           creates=/etc/authbind/byport/80

- name: Change owner and mode of byport file
  file: path=/etc/authbind/byport/80 owner={{ otp_user }} mode=0755

- name: Overwrite upstart service
  template: src=otp.conf.j2 dest=/etc/init/otp.conf

- name: Download OTP Data
  local_action: command aws s3 sync s3://cleanair-otp-data/ ../../otp_data/
  sudo: no
  when: test

- name: Copy OTP Data
  copy: src=./otp_data/ dest="{{ otp_data_dir }}/" owner={{ansible_ssh_user}} group={{ansible_ssh_user}} mode=0664
  when: develop or test

- name: Build OTP Graph
  command: /usr/bin/java -Xmx{{ otp_process_mem }} -jar {{ otp_jarfile }} --build {{ otp_data_dir }}
  args:
    chdir: "{{ otp_bin_dir }}"
  when: develop or test

- name: Copy Built OTP Graph to Host
  fetch: src={{ otp_data_dir }}/Graph.obj dest=../../otp_data/ fail_on_missing=yes flat=yes
  when: develop

- name: Create Graph Directory
  file: path="{{ otp_data_dir}}/{{ otp_router }}" state=directory

- name: Move Graph to Graph Directory
  command: mv {{ otp_data_dir }}/Graph.obj {{ otp_data_dir }}/{{ otp_router }}
  notify: Restart OpenTripPlanner
