---
- name: Create Directory for OSM and GTFS
  file: path={{ otp_data_dir }} state=directory

- name: Copy Feed Validator
  copy: src=validate_feed.py dest="{{ otp_data_dir }}"

- name: Download OTP Data
  local_action: command aws s3 sync s3://cleanair-otp-data ./otp_data/
  sudo: no
  when: production or test

- name: Copy OTP Data
  copy: src=./otp_data/ dest="{{ otp_data_dir }}/" owner={{ansible_ssh_user}} group={{ansible_ssh_user}} mode=0664
  notify: Validate GTFS

- name: Download Philadelphia OSM Data
  get_url: url={{ otp_osm_source }}
           dest={{ otp_osm_filename }}
  notify: Build OTP Graph
