---
- name: Create Directory for OSM and GTFS
  file: path={{ otp_data_dir }} state=directory owner={{ otp_user }}

- name: Copy Feed Validator
  copy: src=validate_feed.py dest="{{ otp_data_dir }}"

- name: Install AuthBind (for serving OTP on port 80)
  apt: pkg=authbind state=present

- name: Touch AuthBind file if it does not exist
  file: path=/etc/authbind/byport/80 state=touch

- name: Change owner and mode of byport file
  file: path=/etc/authbind/byport/80 owner={{ otp_user }} mode=0755

- name: Overwrite systemd service
  template: src=otp.service.j2 dest=/lib/systemd/system/otp.service
  register: otp_service_config

  # We need to reload systemd config for it to see changes.  This (and the 'register' just above)
  # will not be necessary in Ansible 2.2 because there will be a 'systemd' module with a
  # 'daemon_reload' option that we can use instead of 'service'.
- name: Notify systemd of service config changes
  command: systemctl daemon-reload
  when: otp_service_config.changed

- name: Download OTP Data
  local_action: command aws s3 sync s3://cleanair-otp-data/ ../../otp_data/
  sudo: no
  when: test

- name: Copy OTP Data
  copy: src=./otp_data/ dest="{{ otp_data_dir }}/" owner={{ansible_ssh_user}} group={{ansible_ssh_user}} mode=0664
  when: develop or test

- name: Build OTP Graph
  command: /usr/bin/java -Xmx{{ otp_process_mem }} -jar {{ otp_bin_dir }}/otp-{{ otp_version }}{{ otp_jar_suffix }}.jar --build {{ otp_data_dir }}
  args:
    chdir: "{{ otp_bin_dir }}"
  when: develop or test

- name: Copy Built OTP Graph to Host
  fetch: src={{ otp_data_dir }}/Graph.obj dest=../../otp_data/ fail_on_missing=yes flat=yes
  when: develop

- name: Create Graph Directory
  file: path="{{ otp_data_dir}}/{{ otp_router }}" state=directory

- name: Move Graph to Graph Directory
  command: mv {{ otp_data_dir }}/Graph.obj {{ otp_data_dir }}/{{ otp_router }}
  notify: Restart OpenTripPlanner
  when: develop or test

- name: Move Local Graph to Graph Directory
  copy: src=./otp_data/Graph.obj dest="{{ otp_data_dir }}/{{ otp_router }}/Graph.obj" owner={{ansible_ssh_user}} group={{ansible_ssh_user}} mode=0664
  when: production
