---
- name: Create Directory for OSM and GTFS
  file: path={{ otp_data_dir }} state=directory

- name: Download Philadelphia OSM Data
  get_url: url={{ otp_osm_source }}
           dest={{ otp_osm_filename }}
  notify: Build OTP Graph

- name: Copy septa_bus.zip
  copy: src={{ local_gtfs_dir }}/septa_bus.zip dest={{ otp_data_dir }}
  notify: Build OTP Graph

- name: Copy septa_rail.zip
  copy: src={{ local_gtfs_dir }}/septa_rail.zip dest={{ otp_data_dir }}
  notify: Build OTP Graph
