---
- name: Create Directory for OSM and GTFS
  file: path={{ otp_data_dir }} state=directory owner={{ otp_user }}

- name: Copy Feed Validator
  copy: src=validate_feed.py dest="{{ otp_data_dir }}"

- name: Install AuthBind (for serving OTP on port 80)
  apt: pkg=authbind state=present

- name: Touch AuthBind file if it does not exist
  file: path=/etc/authbind/byport/80 state=touch

- name: Change owner and mode of byport file
  file: path=/etc/authbind/byport/80 owner={{ otp_user }} mode=0755

- name: Overwrite systemd service
  template: src=otp.service.j2 dest=/etc/systemd/system/otp.service
  register: otpconf

- name: Reload systemd
  shell: systemctl daemon-reload
  when: otpconf.changed
  notify:
    - Restart OpenTripPlanner

- name: Create data directory (test)
  file: path=./otp_data/ owner={{ansible_user_id}} group={{ansible_user_id}} mode=0664 state=directory

- name: Download OTP Data (test)
  local_action: command aws s3 sync s3://cleanair-otp-data/ ../../otp_data/
  become: no
  when: test

- name: Copy OTP Data (test/develop)
  copy: src=./otp_data/ dest="{{ otp_data_dir }}/" owner={{ansible_user_id}} group={{ansible_user_id}} mode=0664
  when: develop or test

- name: Check for Existing Graph (develop)
  stat:
    path: "{{ otp_data_dir }}/Graph.obj"
  register: graph
  when: develop

- name: Build OTP Graph (test/develop)
  command: /usr/bin/java -Xmx{{ otp_process_mem }} -jar {{ otp_bin_dir }}/{{ otp_jar_name }} --build {{ otp_data_dir }}
  args:
    chdir: "{{ otp_bin_dir }}"
  register: graph_build
  when: test or (develop and not graph.stat.exists)

- name: Copy Built OTP Graph to Host (develop)
  when: develop and graph_build|changed
  synchronize:
    mode: pull
    src: "{{ otp_data_dir }}/Graph.obj"
    dest: "../../otp_data/"
    use_ssh_args: yes

- name: Create Graph Directory
  file: path="{{ otp_data_dir}}/{{ otp_router }}" state=directory

- name: Copy Router Configuration to Graph Directory
  template: src=router-config.json.j2 dest={{ otp_data_dir }}/{{ otp_router }}/router-config.json

- name: Move Graph to Graph Directory (test/develop)
  command: mv {{ otp_data_dir }}/Graph.obj {{ otp_data_dir }}/{{ otp_router }}
  notify: Restart OpenTripPlanner
  when: develop or test

- name: Copy Local Graph to Graph Directory (production)
  copy: src=./otp_data/Graph.obj dest="{{ otp_data_dir }}/{{ otp_router }}/Graph.obj" owner={{ansible_user_id}} group={{ansible_user_id}} mode=0664
  notify: Restart OpenTripPlanner
  when: production
