---
- name: Create Directory for OSM and GTFS
  file: path={{ otp_data_dir }} state=directory

- name: Create Directory for OTP Graph
  file: path={{ otp_graph_dir }} state=directory

- name: Download Philadelphia OSM Data
  get_url: url={{ otp_osm_source }}
           dest={{ otp_osm_filename }}

- name: Save graph-config.xml
  template: src=graph-config.xml.j2 dest={{ otp_data_dir }}/graph-config.xml

- name: Build OTP Graph
  command: /opt/otp/build-old {{ otp_data_dir}}/graph-config.xml
           chdir=/opt/otp/
           creates={{ otp_graph_dir }}/Graph.obj
