---
- name: Validate GTFS
  command: python validate_feed.py
  args:
    chdir: "{{ otp_data_dir }}"

- name: Build OTP Graph
  command: /usr/bin/java -Xmx{{ otp_process_mem }} -jar {{ otp_jarfile }} --build {{ otp_data_dir }}
  args:
    chdir: "{{ otp_bin_dir }}"
  notify: Restart OpenTripPlanner
