---
- hosts: app
  become: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

    - name: Install ACL for ansible file permission controls
      apt:
        state: present
        pkg:
          - acl

  roles:
    - { role: "cac-tripplanner.app"}
