name: Build Graph

on:
  workflow_dispatch:

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    env:
      CAC_OTP_DATA_BUCKET: 'cleanair-otp-data'
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Fetch and process GTFS, OSM and elevation data
        uses: ./.github/actions/fetch-otp-data-action

      # Skip build graph for testing
      # - name: Build graph
      #   run: |
      #     cd deployment/dataproc/graph
      #     docker compose run --rm otp otp --build /var/otp

      - name: Upload new GTFS files, OSM files and graph object to S3
        run: aws s3 sync "otp_data" "s3://$CAC_OTP_DATA_BUCKET"
