name: Build Graph

on:
  workflow_dispatch:

env:
  CAC_OTP_DATA_BUCKET: 'cleanair-otp-data'

jobs:
  get-latest-otp-data:
    name: Fetch & process source data
    uses: ./.github/workflows/fetch-otp-data.yml
    secrets: inherit
  build-graph:
    name: Build & upload OTP graph
    runs-on: ubuntu-latest
    needs: get-latest-otp-data
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download latest GTFS, OSM, and elevation files from S3
        run: aws s3 sync --exclude "Graph.obj" "s3://$CAC_OTP_DATA_BUCKET/" "otp_data"

      - name: Build graph
        run: |
          cd deployment/dataproc/graph
          docker compose run --rm otp otp --build /var/otp

      - name: Upload graph object to S3
        run: aws s3 cp "otp_data/Graph.obj" "s3://$CAC_OTP_DATA_BUCKET/Graph.obj"
